# Generated by Django 5.2 on 2026-09-20 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fileshare',
            name='unique_file_share',
        ),
        migrations.AddConstraint(
            model_name='fileshare',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('file', 'shared_with'), name='unique_active_file_share'),
        ),
    ]
