# Generated by Django 5.2 on 2026-09-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('upload', 'Upload'), ('preview', 'Preview'), ('download', 'Download'), ('share', 'Share'), ('revoke_share', 'Revoke Share'), ('rename', 'Rename'), ('move', 'Move'), ('trash', 'Trash'), ('restore', 'Restore'), ('permanent_delete', 'Permanent Delete'), ('create_folder', 'Create Folder'), ('delete_folder', 'Delete Folder'), ('star', 'Starred'), ('unstar', 'Unstarred')], max_length=30),
        ),
    ]
