# Generated by Django 5.2 on 2026-09-23 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_is_starred'),
        ('folders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('owner', 'folder', 'name'), name='unique_file_name_per_owner_folder'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('folder__isnull', True)), fields=('owner', 'name'), name='unique_root_file_name_per_owner'),
        ),
    ]
