# Generated by Django 5.2 on 2026-09-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
