import os
import re

from django.conf import settings
from rest_framework import serializers

from apps.folders.models import Folder

from .models import File


ALLOWED_EXTENSIONS = {
    ".pdf",
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
    ".docx",
    ".xlsx",
    ".txt",
}

ALLOWED_MIME_TYPES = {
    ".pdf": {"application/pdf"},
    ".jpg": {"image/jpeg"},
    ".jpeg": {"image/jpeg"},
    ".png": {"image/png"},
    ".webp": {"image/webp"},
    ".docx": {
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    },
    ".xlsx": {
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    },
    ".txt": {
        "text/plain",
    },
}

# Characters that are unsafe/unnecessary in user-visible filenames.
UNSAFE_FILENAME_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def sanitize_filename(filename):
    """
    Sanitize a user-visible filename.

    This does NOT change the actual storage path generated by Django.
    It only protects the logical filename stored in the database.
    """
    filename = os.path.basename(filename)

    # Remove control and filesystem-special characters.
    filename = UNSAFE_FILENAME_CHARS.sub("_", filename)

    # Collapse repeated whitespace.
    filename = re.sub(r"\s+", " ", filename).strip()

    # Prevent names such as "." or "..".
    if filename in {"", ".", ".."}:
        raise serializers.ValidationError(
            "Invalid file name."
        )

    # Prevent leading/trailing dots or spaces from causing
    # problematic filesystem behavior.
    filename = filename.strip(" .")

    if not filename:
        raise serializers.ValidationError(
            "Invalid file name."
        )

    return filename[:255]


class FileUploadSerializer(serializers.Serializer):
    folder = serializers.PrimaryKeyRelatedField(
        queryset=Folder.objects.all(),
        required=False,
        allow_null=True,
    )

    name = serializers.CharField(
        max_length=255,
        required=False,
        allow_blank=True,
        trim_whitespace=False,
    )

    file = serializers.FileField(
        required=True,
        allow_empty_file=False,
        max_length=255,
    )

    visibility = serializers.ChoiceField(
        choices=File.Visibility.choices,
        default=File.Visibility.PRIVATE,
    )

    def validate_folder(self, folder):
        request = self.context.get("request")

        if request and folder.owner_id != request.user.id:
            raise serializers.ValidationError(
                "You do not have permission to use this folder."
            )

        return folder

    def validate_name(self, value):
        if not value.strip():
            raise serializers.ValidationError(
                "File name cannot be empty."
            )

        return sanitize_filename(value)

    def validate_file(self, uploaded_file):
        # 1. File-size validation.
        if uploaded_file.size > settings.MAX_UPLOAD_SIZE_BYTES:
            raise serializers.ValidationError(
                f"File size must not exceed "
                f"{settings.MAX_UPLOAD_SIZE_MB} MB."
            )

        # 2. Get and sanitize extension.
        original_name = os.path.basename(uploaded_file.name or "")
        extension = os.path.splitext(original_name)[1].lower()

        if extension not in ALLOWED_EXTENSIONS:
            raise serializers.ValidationError(
                "This file type is not supported."
            )

        # 3. MIME validation.
        #
        # Django/DRF receives this value from the multipart request,
        # so it is useful as a first validation layer but should not
        # be treated as proof of the file's actual contents.
        content_type = (
            uploaded_file.content_type or ""
        ).split(";")[0].strip().lower()

        allowed_mimes = ALLOWED_MIME_TYPES.get(extension, set())

        if content_type not in allowed_mimes:
            raise serializers.ValidationError(
                "The uploaded file has an unsupported MIME type."
            )

        # 4. Sanitize the original filename as well.
        uploaded_file.name = sanitize_filename(original_name)

        return uploaded_file


class FileSerializer(serializers.ModelSerializer):
    owner = serializers.ReadOnlyField(source="owner.username")

    class Meta:
        model = File

        fields = (
            "id",
            "owner",
            "folder",
            "name",
            "file",
            "size",
            "mime_type",
            "visibility",
            "created_at",
            "updated_at",
            "is_deleted",
            "deleted_at",
            "is_starred",
        )

        read_only_fields = (
            "id",
            "owner",
            "size",
            "mime_type",
            "created_at",
            "updated_at",
            "is_deleted",
            "deleted_at",
        )

    def validate_folder(self, folder):
        if folder is None:
            return folder

        request = self.context.get("request")

        if request and folder.owner_id != request.user.id:
            raise serializers.ValidationError(
                "You do not have permission to use this folder."
            )

        return folder


class FileRenameSerializer(serializers.Serializer):
    name = serializers.CharField(
        max_length=255,
        required=True,
        allow_blank=False,
        trim_whitespace=False,
    )

    def validate_name(self, value):
        if not value.strip():
            raise serializers.ValidationError(
                "File name cannot be empty."
            )

        return sanitize_filename(value)


class FileMoveSerializer(serializers.Serializer):
    folder = serializers.PrimaryKeyRelatedField(
        queryset=Folder.objects.all(),
        required=False,
        allow_null=True,
    )

    def validate_folder(self, folder):
        if folder is None:
            return folder

        request = self.context.get("request")

        if request and folder.owner_id != request.user.id:
            raise serializers.ValidationError(
                "You do not have permission to use this folder."
            )

        return folder