import os
import re

from django.conf import settings
from rest_framework import serializers

from apps.folders.models import Folder

from .models import File


ALLOWED_EXTENSIONS = {
    ".pdf",
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
    ".docx",
    ".xlsx",
    ".txt",
}


ALLOWED_MIME_TYPES = {
    ".pdf": {"application/pdf"},
    ".jpg": {"image/jpeg"},
    ".jpeg": {"image/jpeg"},
    ".png": {"image/png"},
    ".webp": {"image/webp"},
    ".docx": {
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    },
    ".xlsx": {
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    },
    ".txt": {
        "text/plain",
    },
}


UNSAFE_FILENAME_CHARS = re.compile(
    r'[<>:"/\\|?*\x00-\x1f]'
)


def sanitize_filename(filename):
    """
    Sanitize a user-visible filename.

    This does NOT change the actual storage path generated by Django.
    It only protects the logical filename stored in the database.
    """

    filename = os.path.basename(filename)

    # Remove unsafe/control characters.
    filename = UNSAFE_FILENAME_CHARS.sub("_", filename)

    # Collapse repeated whitespace.
    filename = re.sub(r"\s+", " ", filename).strip()

    # Prevent empty / "." / ".." names.
    if filename in {"", ".", ".."}:
        raise serializers.ValidationError(
            "Invalid file name."
        )

    # Prevent problematic leading/trailing dots and spaces.
    filename = filename.strip(" .")

    if not filename:
        raise serializers.ValidationError(
            "Invalid file name."
        )

    return filename[:255]


# =========================================================
# FILE UPLOAD
# =========================================================

class FileUploadSerializer(serializers.Serializer):

    folder = serializers.PrimaryKeyRelatedField(
        queryset=Folder.objects.all(),
        required=False,
        allow_null=True,
    )

    name = serializers.CharField(
        max_length=255,
        required=False,
        allow_blank=True,
        trim_whitespace=False,
    )

    file = serializers.FileField(
        required=True,
        allow_empty_file=False,
        max_length=255,
    )

    visibility = serializers.ChoiceField(
        choices=File.Visibility.choices,
        default=File.Visibility.PRIVATE,
    )

    # -----------------------------------------------------
    # Folder permission
    # -----------------------------------------------------

    def validate_folder(self, folder):
        request = self.context.get("request")

        if request and folder.owner_id != request.user.id:
            raise serializers.ValidationError(
                "You do not have permission to use this folder."
            )

        return folder

    # -----------------------------------------------------
    # Filename validation
    # -----------------------------------------------------

    def validate_name(self, value):
        if not value.strip():
            raise serializers.ValidationError(
                "File name cannot be empty."
            )

        return sanitize_filename(value)

    # -----------------------------------------------------
    # Uploaded file validation
    # -----------------------------------------------------

    def validate_file(self, uploaded_file):

        # 1. File-size validation
        if uploaded_file.size > settings.MAX_UPLOAD_SIZE_BYTES:
            raise serializers.ValidationError(
                f"File size must not exceed "
                f"{settings.MAX_UPLOAD_SIZE_MB} MB."
            )

        # 2. Get and validate extension
        original_name = os.path.basename(
            uploaded_file.name or ""
        )

        extension = os.path.splitext(
            original_name
        )[1].lower()

        if extension not in ALLOWED_EXTENSIONS:
            raise serializers.ValidationError(
                "This file type is not supported."
            )

        # 3. MIME validation
        content_type = (
            uploaded_file.content_type or ""
        ).split(";")[0].strip().lower()

        allowed_mimes = ALLOWED_MIME_TYPES.get(
            extension,
            set(),
        )

        if content_type not in allowed_mimes:
            raise serializers.ValidationError(
                "The uploaded file has an unsupported MIME type."
            )

        # 4. Sanitize uploaded filename
        uploaded_file.name = sanitize_filename(
            original_name
        )

        return uploaded_file

    # -----------------------------------------------------
    # DUPLICATE FILENAME VALIDATION
    # -----------------------------------------------------

    def validate(self, attrs):

        request = self.context.get("request")

        if not request or not request.user.is_authenticated:
            return attrs

        # Use explicitly supplied name first.
        name = attrs.get("name")

        # If no custom name was supplied,
        # use the uploaded filename.
        if not name:
            uploaded_file = attrs.get("file")

            if uploaded_file:
                name = sanitize_filename(
                    uploaded_file.name
                )

        if not name:
            return attrs

        # Sanitize again so the database check uses
        # exactly the same filename format.
        name = sanitize_filename(name)

        folder = attrs.get("folder")

        queryset = File.objects.filter(
            owner=request.user,
            name=name,
            is_deleted=False,
        )

        # Root / My Files
        if folder is None:
            queryset = queryset.filter(
                folder__isnull=True
            )

        # Specific folder
        else:
            queryset = queryset.filter(
                folder=folder
            )

        if queryset.exists():
            raise serializers.ValidationError(
                {
                    "name": (
                        f'A file named "{name}" '
                        "already exists in this location."
                    )
                }
            )

        return attrs


# =========================================================
# FILE SERIALIZER
# =========================================================

class FileSerializer(serializers.ModelSerializer):

    owner = serializers.ReadOnlyField(
        source="owner.username"
    )

    class Meta:

        model = File

        fields = (
            "id",
            "owner",
            "folder",
            "name",
            "file",
            "size",
            "mime_type",
            "visibility",
            "created_at",
            "updated_at",
            "is_deleted",
            "deleted_at",
            "is_starred",
        )

        read_only_fields = (
            "id",
            "owner",
            "size",
            "mime_type",
            "created_at",
            "updated_at",
            "is_deleted",
            "deleted_at",
        )

    def validate_folder(self, folder):

        if folder is None:
            return folder

        request = self.context.get("request")

        if request and folder.owner_id != request.user.id:
            raise serializers.ValidationError(
                "You do not have permission to use this folder."
            )

        return folder


# =========================================================
# FILE RENAME
# =========================================================

class FileRenameSerializer(serializers.Serializer):

    name = serializers.CharField(
        max_length=255,
        required=True,
        allow_blank=False,
        trim_whitespace=False,
    )

    def validate_name(self, value):

        if not value.strip():
            raise serializers.ValidationError(
                "File name cannot be empty."
            )

        return sanitize_filename(value)


# =========================================================
# FILE MOVE
# =========================================================

class FileMoveSerializer(serializers.Serializer):

    folder = serializers.PrimaryKeyRelatedField(
        queryset=Folder.objects.all(),
        required=False,
        allow_null=True,
    )

    def validate_folder(self, folder):

        if folder is None:
            return folder

        request = self.context.get("request")

        if request and folder.owner_id != request.user.id:
            raise serializers.ValidationError(
                "You do not have permission to use this folder."
            )

        return folder