from django.urls import path

from .views import (
    FileListCreateView,
    FileDetailView,
    FileRestoreView,
    FileDownloadView,
    FilePreviewView,
    FileRenameView,
    FileMoveView,
    FileTrashView,
    FilePermanentDeleteView,
    FileRecentView,
    FileStarToggleView,
    FileStarredView,
    FileStorageView,
)


urlpatterns = [
    path(
        "",
        FileListCreateView.as_view(),
        name="file-list-create",
    ),
    path(
        "trash/",
        FileTrashView.as_view(),
        name="file-trash",
    ),
    path(
        "<int:pk>/",
        FileDetailView.as_view(),
        name="file-detail",
    ),
    path(
        "<int:pk>/restore/",
        FileRestoreView.as_view(),
        name="file-restore",
    ),
    path(
        "<int:pk>/download/",
        FileDownloadView.as_view(),
        name="file-download",
    ),
    path(
        "<int:pk>/preview/",
        FilePreviewView.as_view(),
        name="file-preview",
    ),
    path(
        "<int:pk>/rename/",
        FileRenameView.as_view(),
        name="file-rename",
    ),
    path(
        "<int:pk>/move/",
        FileMoveView.as_view(),
        name="file-move",
    ),
    path(
        "<int:pk>/permanent-delete/",
        FilePermanentDeleteView.as_view(),
        name="file-permanent-delete",
    ),
    path("recent/", FileRecentView.as_view(), name="file-recent"),
    path(
    "<int:pk>/star/",
    FileStarToggleView.as_view(),
    name="file-star-toggle",
),
    path(
    "starred/",
    FileStarredView.as_view(),
    name="file-starred",
),
    path(
    "storage/",
    FileStorageView.as_view(),
    name="file-storage",
),
]